update how to get henakaku token only jp page
henkaku-center/henkaku-community pull request #3
Opened 2021-12-07 11:26 UTC by TatsuyaIshibe

# What
- Discordの会話のオンボーディングを元に内容を修正

2021-12-07 11:27 UTC, TatsuyaIshibe commented
@wataruoguchi このような形でいかがでしょうか？？

2021-12-07 16:49 UTC, wataruoguchi approved these changes
更新ありがとうございます！素晴らしい。英語版にも反映させたいですね

2021-12-07 16:49 UTC, wataruoguchi commented on henkaku-token-ja.md
> +    - https://support.discord.com/hc/ja/articles/217916488-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%A8%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E8%A8%AD%E5%AE%9A
nit pickingですが、Markdownのリンク記法を利用することでスッキリします。

```md
注意: 初期設定がDMをブロックしている可能性があるので[こちらのページ](https://support.discord.com/hc/ja/articles/217916488-%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%A8%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E8%A8%AD%E5%AE%9A)を参考に許可してください。
```

2021-12-07 21:08 UTC, wataruoguchi commented
@TatsuyaIshibe ドキュメントチェックをしているようですのでmergeは待っていただけますか？

2021-12-08 00:15 UTC, wataruoguchi commented
@TatsuyaIshibe 待っている間、英語でもコンテンツを作ることは可能ですか？admin channelで英語ネイティブのユーザーに英語チェックしてもらってcommitできたら最高です。もし大変でしたらdiscord上でお声がけください！私も協力します。

2021-12-08 05:28 UTC, TatsuyaIshibe commented
@wataruoguchi 英語も時間見つけてやりますね！

2021-12-09 21:08 UTC, Joi commented
Are you waiting for me to merge or will you merge when ready?

2021-12-09 21:14 UTC, wataruoguchi commented
@Joi  the latter! If things are good either Ishibe san or I will merge :)

2021-12-09 21:15 UTC, Joi reviewed
👋wellcome -> 👋welcome
hit the `!register` command -> go to the #join channel and type `!register`.
You will get a DM from an account called Collab.Land. -> You will get a DM from an account called coinvise-bot.
:note: Some scam users with the same name as the bot may send you a message, so please check visually before clicking on the link to see if it is a bot. -> :note: Some scammers with the same name as the bot may send you a message, so please check the name of the bot and confirm it is coinvise-bot#4309 - also make sure it is the bot the messaged you right after you did the `!register` command.

2021-12-09 22:01 UTC, Joi requested changes
will give you a $HENAKU token -> will give can give you $HENAKU tokens

2021-12-09 22:13 UTC, Joi commented
Actually, I'll make the changes directly in a few min.

2021-12-09 22:35 UTC, Joi approved these changes

2021-12-09 22:35 UTC, Joi commented
So I edited the English but I added some new stuff so maybe it's a bit out of sync with the Japanese now. :-) Can you take a look @wataruoguchi and @TatsuyaIshibe?

2021-12-09 22:57 UTC, wataruoguchi commented
@TatsuyaIshibe I've just updated the Japanese page based on what @Joi has changed. Would you double check and merge it, please? Good work all!

2021-12-10 02:50 UTC, TatsuyaIshibe commented
LGTM!

2021-12-10 02:51 UTC, merged